"""Add student conceptual understanding analytics tables

Revision ID: 5c1134627a54
Revises: 
Create Date: 2026-06-19 21:47:26.503929

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import app.core.models


# revision identifiers, used by Alembic.
revision: str = '5c1134627a54'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('concept_scores',
    sa.Column('id', app.core.models.GUID(), nullable=False),
    sa.Column('student_id', app.core.models.GUID(), nullable=False),
    sa.Column('chapter_id', app.core.models.GUID(), nullable=False),
    sa.Column('class_id', app.core.models.GUID(), nullable=False),
    sa.Column('transcript', sa.Text(), nullable=True),
    sa.Column('clarity_score', sa.Float(), nullable=True),
    sa.Column('accuracy_score', sa.Float(), nullable=True),
    sa.Column('depth_score', sa.Float(), nullable=True),
    sa.Column('overall_score', sa.Float(), nullable=True),
    sa.Column('llm_feedback', sa.Text(), nullable=True),
    sa.Column('attempt_number', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['chapter_id'], ['chapters.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['class_id'], ['classes.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['student_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_concept_scores_chapter_id'), 'concept_scores', ['chapter_id'], unique=False)
    op.create_index(op.f('ix_concept_scores_class_id'), 'concept_scores', ['class_id'], unique=False)
    op.create_index(op.f('ix_concept_scores_student_id'), 'concept_scores', ['student_id'], unique=False)
    op.create_table('student_topic_clusters',
    sa.Column('id', app.core.models.GUID(), nullable=False),
    sa.Column('class_id', app.core.models.GUID(), nullable=False),
    sa.Column('chapter_id', app.core.models.GUID(), nullable=False),
    sa.Column('cluster_label', sa.String(length=50), nullable=False),
    sa.Column('student_ids', sa.JSON(), nullable=False),
    sa.Column('avg_score', sa.Float(), nullable=False),
    sa.Column('computed_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['chapter_id'], ['chapters.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['class_id'], ['classes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_student_topic_clusters_chapter_id'), 'student_topic_clusters', ['chapter_id'], unique=False)
    op.create_index(op.f('ix_student_topic_clusters_class_id'), 'student_topic_clusters', ['class_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_student_topic_clusters_class_id'), table_name='student_topic_clusters')
    op.drop_index(op.f('ix_student_topic_clusters_chapter_id'), table_name='student_topic_clusters')
    op.drop_table('student_topic_clusters')
    op.drop_index(op.f('ix_concept_scores_student_id'), table_name='concept_scores')
    op.drop_index(op.f('ix_concept_scores_class_id'), table_name='concept_scores')
    op.drop_index(op.f('ix_concept_scores_chapter_id'), table_name='concept_scores')
    op.drop_table('concept_scores')
    # ### end Alembic commands ###
